# Generated by Django 5.0.7 on 2024-08-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='Unknown', max_length=255, unique=True)),
                ('social_link', models.URLField(default='https://www.instagram.com/')),
            ],
            options={
                'verbose_name': 'Artist',
                'ordering': ['id'],
            },
        ),
    ]
