# Generated by Django 4.2.4 on 2023-11-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='Unknown', max_length=255, unique=True)),
                ('socialLink', models.URLField(default='https://www.instagram.com')),
            ],
            options={
                'verbose_name': 'Artist',
                'ordering': ['artist_name'],
            },
        ),
    ]
