# Generated by Django 4.2.4 on 2023-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'verbose_name': 'Artist'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='socialLink',
            field=models.URLField(default='https://www.instagram.com'),
        ),
    ]
