# Generated by Django 4.2.4 on 2024-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
