# Generated by Django 5.0.7 on 2024-08-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_social_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['id'], 'verbose_name': 'Artist'},
        ),
    ]
