# Generated by Django 4.2.4 on 2023-09-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_options_alter_artist_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='socialLink',
            field=models.URLField(default='https://www.instagram.com', verbose_name='Social Media'),
        ),
    ]
