# Generated by Django 4.2.4 on 2023-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_name_alter_artist_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Unknown', max_length=200, unique=True, verbose_name='Artist Name'),
        ),
    ]
