# Generated by Django 4.2.4 on 2023-11-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='socialLink',
        ),
        migrations.AddField(
            model_name='artist',
            name='social_link',
            field=models.URLField(default='https://www.instagram.com'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Unknown', max_length=255, unique=True),
        ),
    ]
