# Generated by Django 4.2.4 on 2023-11-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(default='New Album', max_length=255)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('release_datetime', models.DateTimeField(default='2000-12-12')),
                ('cost', models.FloatField()),
                ('is_approved', models.BooleanField(default=False, help_text='Approve the album if its name is not explicit')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
            options={
                'verbose_name': 'Album',
                'ordering': ['album_name'],
            },
        ),
    ]
