# Generated by Django 4.2.4 on 2024-07-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(default='New Album', max_length=200)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('release_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('cost', models.FloatField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artists.artist')),
            ],
            options={
                'verbose_name': 'Album',
                'ordering': ['album_name'],
            },
        ),
    ]
