# Generated by Django 4.2.4 on 2024-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(default='New Album', max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
