# Generated by Django 4.2.4 on 2024-07-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
