# Generated by Django 4.2.4 on 2023-12-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(default='New Album', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
