# Generated by Django 5.0.7 on 2024-08-31 12:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='songs/audio/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='songs/'),
        ),
    ]
