# Generated by Django 4.2.4 on 2023-11-18 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['album_name'], 'verbose_name': 'Album'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
        migrations.AddField(
            model_name='album',
            name='album_name',
            field=models.CharField(default='New Album', max_length=20),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='artists.artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
