# Generated by Django 4.2.4 on 2023-08-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_options_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
