# Generated by Django 4.2.4 on 2024-07-30 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_album_name_alter_album_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Song', max_length=150)),
                ('image', models.ImageField(upload_to='songs/%y/%m/%d')),
                ('audio_file', models.FileField(upload_to='audio/%y/%m/%d')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='albums.album')),
            ],
        ),
    ]
