# Generated by Django 4.2.4 on 2024-07-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_album_name_alter_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
    ]
