# Generated by Django 4.2.4 on 2023-08-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_release_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
