# Generated by Django 4.2.4 on 2024-07-31 15:06

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='songs/audio/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
