# Generated by Django 4.2.4 on 2023-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_album_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_datetime',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
