# Generated by Django 4.2.4 on 2023-11-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_album_release_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_datetime',
            field=models.DateTimeField(auto_created=True, default='2000/12/12'),
        ),
    ]
