# Generated by Django 4.2.4 on 2023-11-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artist_name'),
        ('albums', '0011_alter_album_creation_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='New Album', max_length=255),
        ),
    ]
