# Generated by Django 4.2.4 on 2023-11-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_alter_album_artist_alter_album_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['album_name'], 'verbose_name': 'Album'},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='album_name',
        ),
    ]
