# Generated by Django 4.2.4 on 2023-11-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_alter_album_options_rename_name_album_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
